# Generated by Django 3.2.5 on 2021-07-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp1',
            name='HumidityHigh',
            field=models.CharField(default='100', max_length=64, verbose_name='HumidityHigh'),
        ),
        migrations.AddField(
            model_name='temp1',
            name='HumidityLOW',
            field=models.CharField(default='1', max_length=64, verbose_name='HumidityLOW'),
        ),
        migrations.AddField(
            model_name='temp1',
            name='TemperatureHigh',
            field=models.CharField(default='100', max_length=64, verbose_name='TemperatureHigh'),
        ),
        migrations.AddField(
            model_name='temp1',
            name='TemperatureLOW',
            field=models.CharField(default='1', max_length=64, verbose_name='TemperatureLOW'),
        ),
        migrations.AddField(
            model_name='temp2',
            name='HumidityHigh',
            field=models.CharField(default='100', max_length=64, verbose_name='HumidityHigh'),
        ),
        migrations.AddField(
            model_name='temp2',
            name='HumidityLOW',
            field=models.CharField(default='1', max_length=64, verbose_name='HumidityLOW'),
        ),
        migrations.AddField(
            model_name='temp2',
            name='TemperatureHigh',
            field=models.CharField(default='100', max_length=64, verbose_name='TemperatureHigh'),
        ),
        migrations.AddField(
            model_name='temp2',
            name='TemperatureLOW',
            field=models.CharField(default='1', max_length=64, verbose_name='TemperatureLOW'),
        ),
        migrations.AddField(
            model_name='temp3',
            name='HumidityHigh',
            field=models.CharField(default='100', max_length=64, verbose_name='HumidityHigh'),
        ),
        migrations.AddField(
            model_name='temp3',
            name='HumidityLOW',
            field=models.CharField(default='1', max_length=64, verbose_name='HumidityLOW'),
        ),
        migrations.AddField(
            model_name='temp3',
            name='TemperatureHigh',
            field=models.CharField(default='100', max_length=64, verbose_name='TemperatureHigh'),
        ),
        migrations.AddField(
            model_name='temp3',
            name='TemperatureLOW',
            field=models.CharField(default='1', max_length=64, verbose_name='TemperatureLOW'),
        ),
    ]
